### ISSUE TITLE
I recieve th

### ISSUE THREAD

**Issue by mrW0RLDWlDE** [Mr-Proxy-source/BadUSB-Payloads#5]
![image](https://github.com/user-attachments/assets/e5b708fa-b5eb-44e3-951f-12c548a7170d)

**Comment by mrW0RLDWlDE** [comment]
this is what I see after running script

**Comment by mrW0RLDWlDE** [comment]
Google Exfil payload btw

**Comment by Mr-Proxy-source** [comment]
Ye they are updating their api, i will update it when they finish updates. Till then use discord webhook

**Comment by mrW0RLDWlDE** [comment]
i pasted the webhook url into the code originally and thats what I got

**Comment by mrW0RLDWlDE** [comment]
nvm i fixed it but now i get this from my webhook
![image](https://github.com/user-attachments/assets/168656ad-3c40-4a27-af5a-d5b8a4e997e5)

**Comment by Mr-Proxy-source** [comment]
Yeah you will have to wait because i would do it by uploading to discord webhook, but the file size is too big i will try to fix gofile or i will find alternative.

**Comment by mrW0RLDWlDE** [comment]
Okay thank you, take your time
